export type ProductType = {
  id?: string;
  productId?: string;
  productImage?: string[];
  productName?: string;
  productPrice?: number | string;
  productHexCodes?: string[];
  productCode?: string;
  productInfo?: string;
  info?: string[];
  productNotice?: string;
  notice?: string[];
  productDetails?: string;
  details?: string[];
  productMaterials?: string;
  materials?: string[];
  productOrigin?: string;
  productManufacturer?: string;
  productDeliveryMethod?: string;
  productDeliveryPrice?: number | string;
};
